### PR TITLE
Got Instagram API to return object with data

### PR DESCRIPTION
**Pull request by skylerbraden**
Hey Michael,

Just wanted to let you know that I finally got it working! It was, in the end, the `vm = this;` issue. Is there a better way to write this with `$scope` or is the `vm` was the best practice?

Thank for all your help!
Skyler

### CODE REVIEW

**Comment by MichaelCPell** [comment]
I don't get it, so adding `vm = this`  causes the problem or is it the solution

**Comment by skylerbraden** [comment]
It is the solution (seemingly). I also changed my function declaration to `vm.instaApi` and `jsonpCallback: "vm.instaApi",`

**Comment by MichaelCPell** [comment]
woah, that was a bold move.  Have you made certain which is the one that solves the problem?

**Comment by skylerbraden** [comment]
I belive I had to prepend both of the function references with `vm.` for it to work. I started just with the function declaration but then the `.$ajax` object didn't recognize `instaApi` until I added `vm.` to it.

**Comment by MichaelCPell** [comment]
that is super interesting and sheds light on some part of the mechanics that I clearly do not understand.  Excellent work man!

**Comment by MichaelCPell** [comment]
merged 👍

**Comment by MichaelCPell** [comment]
that is super interesting and sheds light on some part of the mechanics
that I clearly do not understand.  Excellent work man!

Michael Pell
1 (919) 408 7153
Skype: MichaelCPell

**Comment by skylerbraden** [comment]
The `vm` trick I learned from you on a previous AngularJS project!

Thanks for merging. Do I just need to do a `git pull` now to update my local?

**Comment by MichaelCPell** [comment]
if you need to.  You can also just merge it from local.

But the real innovation here was prefacing the `callback` function with
`vm`.  I don't know how long it would have taken me to try that.



Michael Pell
1 (919) 408 7153
Skype: MichaelCPell

**Comment by skylerbraden** [comment]
Ah yes, that makes sense.

We maybe I understand a little more than I think. I feel braindead half the time!

**Pull request merged**
